name: RPM build
on: [push]
env:
  ARTIFACTORY_URL: https://rpmb.jfrog.io
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  RL9: 9.6.20250531
  RL9TAG: 9.6.20250531
  RL10: 10.0.20250606
  RL10TAG: 10.0.20250606
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compose-file: docker-compose.php84.yml
            repo: php84custom
            build: rocky10build
            uploader: rocky10bintray
            repo_path: rocky/10
          - compose-file: docker-compose.php84.yml
            repo: php84custom
            build: rocky9build
            uploader: rocky9bintray
            repo_path: rocky/9
          - compose-file: docker-compose.php83.yml
            repo: php83custom
            build: rocky10build
            uploader: rocky10bintray
            repo_path: rocky/10
          - compose-file: docker-compose.php83.yml
            repo: php83custom
            build: rocky9build
            uploader: rocky9bintray
            repo_path: rocky/9
          - compose-file: docker-compose.php82.yml
            repo: php82custom
            build: rocky10build
            uploader: rocky10bintray
            repo_path: rocky/10
          - compose-file: docker-compose.php82.yml
            repo: php82custom
            build: rocky9build
            uploader: rocky9bintray
            repo_path: rocky/9
          - compose-file: docker-compose.php81.yml
            repo: php81custom
            build: rocky10build
            uploader: rocky10bintray
            repo_path: rocky/10
          - compose-file: docker-compose.php81.yml
            repo: php81custom
            build: rocky9build
            uploader: rocky9bintray
            repo_path: rocky/9
    env:
      BUILD_COMPOSE_FILE: ${{ matrix.compose-file }}
      BINTRAY_REPO: ${{ matrix.repo }}
      BUILD: ${{ matrix.build }}
      UPLOADER: ${{ matrix.uploader }}
      REPO_PATH: ${{ matrix.repo_path }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: docker compose -f $BUILD_COMPOSE_FILE build --no-cache $BUILD
      - run: docker compose -f $BUILD_COMPOSE_FILE up --exit-code-from $BUILD $BUILD
      - run: docker compose -f rpmbuild/docker-compose.yml pull $UPLOADER
      - run: docker compose -f rpmbuild/docker-compose.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL -e REPO_PATH=$REPO_PATH $UPLOADER
